CREATE OR REPLACE FUNCTION createdTrigger()
RETURNS TRIGGER as $createdTrigger$
    BEGIN
        NEW.created_at = CURRENT_TIMESTAMP;
        RETURN NEW;
    END;
$createdTrigger$ LANGUAGE plpgsql;

CREATE TRIGGER crtTrigAkun BEFORE INSERT ON akun FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigProduk BEFORE INSERT ON produk FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigDiskusi BEFORE INSERT ON diskusi FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigTestimoni BEFORE INSERT ON testimoni FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigtransaksi BEFORE INSERT ON transaksi FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigDiskon BEFORE INSERT ON diskon FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigKategori BEFORE INSERT ON kategori FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigJenis_Produk BEFORE INSERT ON jenis_produk FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigLampiran BEFORE INSERT ON lampiran FOR EACH ROW EXECUTE PROCEDURE createdTrigger();
CREATE TRIGGER crtTrigJasa_Kirim BEFORE INSERT ON jasa_kirim FOR EACH ROW EXECUTE PROCEDURE createdTrigger();